Vagrant.configure("2") do |config|
  # Use CoreOS to run Docker
  config.vm.box = "coreos-alpha"
  config.vm.box_url = "http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

  # Use static IP for CoreOS VirtualBox VM
  config.vm.network :private_network, ip: "10.1.1.51"

  # Mount the whole project folder in the CoreOS VM as a shared folder
  config.vm.synced_folder "../", "/home/core/share", id: "core", :nfs => true,  :mount_options   => ['nolock,vers=3,udp']

  # Uncomment if you want to map ports from CoreOS to Mac OS X
  #config.vm.network :forwarded_port, guest: 80, host: 80

  config.vm.provider :virtualbox do |vb, override|
    # Speed up network access
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # Adjust amount of memory available to CoreOS/Docker
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  # Disable VirtualBox Guest Additions auto-updater
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # Start docker using systemd
  config.vm.provision "file", source: "docker-tcp.socket", destination: "/tmp/docker-tcp.socket"
  config.vm.provision "shell",  inline: "cp /tmp/docker-tcp.socket /etc/systemd/system/docker-tcp.socket"
  config.vm.provision "shell",  inline: "sudo systemctl enable docker-tcp.socket"
  config.vm.provision "shell",  inline: "sudo systemctl stop docker"
  config.vm.provision "shell",  inline: "sudo systemctl start docker-tcp.socket"
  config.vm.provision "shell",  inline: "sudo systemctl start docker"
end
